import { Booking, DriverProfile } from "./types";

export const demoDriver: DriverProfile = {
  id: "DRV-1092",
  name: "Tariq Akmal",
  permitNumber: "AUH-LIMO-44219",
  assignedVehicle: "Abu Dhabi 6 - 48321",
  companyName: "Carmak Limousine Operations",
};

export const initialBookings: Booking[] = [
  {
    id: "BKG-1001",
    reference: "PRI-1001",
    sourceChannel: "OPERATOR_PRIVATE",
    customerName: "Nadia Hassan",
    customerMobileNumber: "+971501112233",
    nationality: "UAE",
    pickupLocationDescription: "Rosewood Abu Dhabi, main entrance",
    dropoffLocationDescription: "Abu Dhabi Airport Terminal A",
    pickupTimeLocal: "2026-03-13 14:30",
    paymentMode: "corporate",
    totalAmount: 220,
    bookingStatus: "assigned",
    syncStatus: "synced",
    createdBy: "operator",
    driverName: "Tariq Akmal",
    vehiclePlateNumber: "48321",
    emiratesIdNumber: "784-1992-1234567-1",
  },
  {
    id: "BKG-1002",
    reference: "HOT-1044",
    sourceChannel: "HOTEL",
    customerName: "Passenger details not provided",
    customerMobileNumber: "",
    nationality: "",
    pickupLocationDescription: "Four Seasons reception",
    dropoffLocationDescription: "Yas Marina Circuit",
    pickupTimeLocal: "2026-03-13 16:10",
    paymentMode: "card",
    totalAmount: 175,
    bookingStatus: "assigned",
    syncStatus: "synced",
    createdBy: "operator",
    driverName: "Tariq Akmal",
    vehiclePlateNumber: "48321",
  },
  {
    id: "BKG-1003",
    reference: "PHN-1099",
    sourceChannel: "PHONE",
    customerName: "Amina Noor",
    customerMobileNumber: "+971544440099",
    nationality: "Pakistan",
    pickupLocationDescription: "Corniche Family Park Gate 2",
    dropoffLocationDescription: "Saadiyat Beach Club",
    pickupTimeLocal: "2026-03-13 18:45",
    paymentMode: "cash",
    totalAmount: 160,
    bookingStatus: "passenger_verified",
    syncStatus: "pending",
    createdBy: "operator",
    driverName: "Tariq Akmal",
    vehiclePlateNumber: "48321",
    passportNumber: "551209134",
    verificationNotes: "Passenger confirmed. Background sync pending.",
  },
];
